### PR TITLE
gh-22: Amend float detection patch to use private Autoconf variables

### PR DESCRIPTION
**Pull request by erlend-aasland**

### CODE REVIEW

**Comment by erlend-aasland** [comment]
@danamelang: I think this is a safer choice; what do you think of upstreaming this amendment?

**Comment by corona10** [comment]
Hmm by the way, please take a look at this issue too: https://github.com/python/cpython-devcontainers/issues/29
Since we already upgrade the autoconf image to 24.04, we may need to modify related CI code or should be fixed from this repo side.

**Review by corona10 — APPROVED** [review]

**Comment by erlend-aasland** [comment]
Thanks for the review, Donghee. I'll give Dan a chance to chime in before landing this.

**Comment by erlend-aasland** [comment]
Actually, I don't think we should do this; most macros in autoconf-archive use `EXEEXT` and not `ac_exeext`. Perhaps a workaround in `configure.ac` is the best solution after all.

**Comment by erlend-aasland** [comment]
> [...] Perhaps a workaround in `configure.ac` is the best solution after all.

See:

- https://github.com/python/cpython/pull/125995

**Pull request closed without merging**
